# Site settings
author: Owen Cruse
title: DEVeloping my skills
header-img: img/home-bg.png
email: ocruse7@gmail.com
copyright_name: Owen Cruse
description: > # this means to ignore newlines until "baseurl:"
  My thoughts as an software development student
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ocruse7

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
